### ISSUE TITLE
update copyright year in examples and templates to 2020

### ISSUE THREAD

**Issue by eckelcu** [CiscoSE/Cisco-Sample-Code#3]
### Description

The copyright year in the LICENSE file that results when people copy files or use cookie cutter is 2018. It should now be 2020.

The following PRs address this:
https://github.com/CiscoSE/cisco-sample-code/pull/1
https://github.com/CiscoSE/cisco-sample-code/pull/2

**Comment by cmlccie** [comment]
The license was created in 2018 and has not changed since then. The copyright should only be updated when the work is updated.

**Comment by eckelcu** [comment]
I agree for a code repo in general, but given the purpose of this repo, I think it is important to update to reflect the current year. People use this repo as the basis for creating a new repo. Whether the make a copy/clone of the repo or use cookiecutter, they end up with a repo with a LICENSE file that has a 2018 copyright year. This is not appropriate. Their new repo should have a copyright year of 2020.

**Comment by cmlccie** [comment]
It is appropriate.  I have previously confirmed this with Cisco Legal.  The copyright notice in question applies to the ***license*** not the created work.  Their created works should be contain a copyright notice with the correct year; however, the license added to those works caries its own copyright with the year it was created or last modified.

**Comment by cmlccie** [comment]
For example or comparative reference, please see other licenses like the [Apache v2.0](https://www.apache.org/licenses/LICENSE-2.0.txt).  This is the latest version of the license.  It has not changed since 2004.  Therefore it contains (albeit not a copyright notice) the year it was last updated.  A better example might the the [GPL v3.0](https://www.gnu.org/licenses/gpl-3.0.txt) license, last updated in 2007, which is listed with a copyright notice for the year it was created/updated 2007.

If you have concerns or believe that I am in error in this recommendation, I recommend you reach out to Cisco Legal.  I am glad to provide you the contact who created the license, and who previously instructed me accordingly.
